require('@next/env').loadEnvConfig(process.cwd());
const fs = require('node:fs');
const nim = require('../lib/nim.ts');
const { prisma } = require('../lib/db.ts');
const { POST } = require('../app/api/draft/route.ts');
const { StructureSchema } = require('../lib/essay-types.ts');
const { STRUCTURE_SYSTEM, structureUserPrompt } = require('../lib/prompts.ts');
const projectId = process.argv[2];
const model = process.argv.find((argument)=>argument.startsWith('--model='))?.slice(8);
if (!projectId) throw new Error('Supply the project ID to test.');
const directory = 'tests/artifacts/current-run';
fs.mkdirSync(directory, {recursive:true});
const actual = nim.nimChatLong;
let index=0;
nim.nimChatLong = async (params) => {
  const step=++index;
  const stage=params.system.includes('select evidence before')?'selection':params.system.includes('source-grounding auditor')?'audit':'writer';
  console.log(`Starting ${step} ${stage}`);
  fs.writeFileSync(`${directory}/${step}-${stage}-input.txt`,params.user);
  const raw=await actual({...params,...(model?{model}:{}),onAttempt:(attempt)=>{console.log(`${step} ${stage}: service attempt ${attempt}`);params.onAttempt?.(attempt);}});
  fs.writeFileSync(`${directory}/${step}-${stage}.json`,raw);
  console.log(`Finished ${step} ${stage}: ${raw.length} characters`);
  return raw;
};
(async()=>{
  const project=await prisma.project.findUnique({where:{id:projectId}});
  if (!project) throw new Error('Project not found.');
  const sources=await prisma.source.findMany({where:{projectId}});
  const minimumFootnotes=Number(process.argv.find(a=>a.startsWith('--minimum-footnotes='))?.split('=')[1]||1);
  const minimumSources=Number(process.argv.find(a=>a.startsWith('--minimum-sources='))?.split('=')[1]||1);
  const input={minimumFootnotes,minimumSources,topic:project.topic,instructionText:project.instruction,extraInstructions:'',wordTarget:project.wordTarget};
  console.log('Generating the source-neutral outline.');
  const structure=process.argv.includes('--reuse-outline') ? JSON.parse(fs.readFileSync(`${directory}/outline.json`,'utf8')) : await nim.completeJson({system:STRUCTURE_SYSTEM,user:structureUserPrompt(input),schema:StructureSchema,thinking:false,maxTokens:3000,...(model?{model}:{})});
  fs.writeFileSync(`${directory}/outline.json`,JSON.stringify(structure,null,2));
  const response=await POST(new Request('http://localhost/api/draft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,structureJson:JSON.stringify(structure),sourcesJson:JSON.stringify(sources),projectId})}));
  const result=await response.json();
  fs.writeFileSync(`${directory}/result.json`,JSON.stringify(result,null,2));
  console.log(JSON.stringify({status:response.status,wordCount:result.wordCount,versionId:result.versionId,error:result.error}));
  if(response.status!==200)process.exitCode=1;
})().catch(error=>{console.error(error.message);process.exitCode=1;});
